name: flutter_application_one
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  hive_ce: ^2.2.3
  hive_ce_flutter: ^1.1.0
  provider: ^6.0.5 
  # firebase_auth: ^6.1.2
  # firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  # sqflite: ^2.4.2
  toggle_switch: ^2.3.0
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^3.0.3
  riverpod_generator: ^3.0.0-dev.11
  # share_plus: ^10.0.0
  # android_intent_plus: ^3.0.0

dev_dependencies:
  analyzer: ^6.4.1
  hive_ce_generator: ^1.4.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  custom_lint:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Audiowide
    fonts:
      - asset: assets/fonts/Audiowide-Regular.ttf
  - family: Arial
    fonts:
      - asset: assets/fonts/ArialCE.ttf
      - asset: assets/fonts/arialceb.ttf
      - asset: assets/fonts/ArialCEBoldItalic.ttf
      - asset: assets/fonts/ArialCEItalic.ttf
      - asset: assets/fonts/ArialCEMTBlack.ttf
  
  assets:
      - assets/images/broadcastImages/Highschool_dxd_logo.png
      - assets/images/broadcastImages/Highschool_dxd_born_logo.png
      - assets/images/broadcastImages/Highschool_dxd_new_logo.png
      - assets/images/broadcastImages/Highschool_dxd_hero_logo.png
      - assets/images/broadcastImages/SoloLeveling_logo.jpg
      - assets/images/broadcastImages/UQHolder_logo.png
      - assets/images/broadcastImages/TheEminenceInShadow_logo.png
      - assets/images/broadcastImages/AkameGaKill_logo.png
      - assets/images/broadcastImages/KonoSuba_logo.png
      - assets/images/broadcastImages/CallOfTheNight_logo.png
      - assets/images/broadcastImages/Shinchou_Yuusha_logo.png
      - assets/images/broadcastImages/JujutsuKaisen.png
      - assets/images/broadcastImages/HellsParadise.png
      - assets/images/broadcastImages/DragonBall.png
      - assets/images/broadcastImages/DragonBallZ.png
      - assets/images/broadcastImages/DragonBallZKai.png
      - assets/images/broadcastImages/DragonBallGT.png
      - assets/images/broadcastImages/DragonBallSuper.png
      - assets/images/broadcastImages/DragonBallDaima.png
      - assets/images/broadcastImages/MonsterMaedchen.png 
      - assets/images/profile2.png
      - assets/images/shareIcons/facebook.png
      - assets/images/shareIcons/instagram.png
      - assets/images/shareIcons/telegram.png
      - assets/images/shareIcons/tiktok.png
      - assets/images/shareIcons/x-icon.png
      # - assets/images/shareIcons/twitter.png
      # - assets/images/shareIcons/whatsapp.png
      - assets/sounds/bFrog.mp3
      # - assets/sounds/blob.mp3
      # - assets/sounds/swoosh.mp3
      # - assets/sounds/crystal.mp3
      # - assets/sounds/digital.mp3