name: flutter_application_one
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Audiowide
    fonts:
      - asset: assets/fonts/Audiowide-Regular.ttf
  - family: Arial
    fonts:
      - asset: assets/fonts/ArialCE.ttf
      - asset: assets/fonts/arialceb.ttf
      - asset: assets/fonts/ArialCEBoldItalic.ttf
      - asset: assets/fonts/ArialCEItalic.ttf
      - asset: assets/fonts/ArialCEMTBlack.ttf
  
  assets:
      - assets/images/broadcastImages/Highschool_dxd_logo.png
      - assets/images/broadcastImages/Highschool_dxd_born_logo.png
      - assets/images/broadcastImages/Highschool_dxd_new_logo.png
      - assets/images/broadcastImages/Highschool_dxd_hero_logo.png
      - assets/images/broadcastImages/SoloLeveling_logo.jpg
      - assets/images/broadcastImages/UQHolder_logo.png
      - assets/images/broadcastImages/TheEminenceInShadow_logo.png
      - assets/images/broadcastImages/AkameGaKill_logo.png
      - assets/images/broadcastImages/KonoSuba_logo.png
      - assets/images/broadcastImages/CallOfTheNight_logo.png
      - assets/images/broadcastImages/Shinchou_Yuusha_logo.png
      - assets/images/profile2.png
      # - assets/sounds/blob.mp3
      # - assets/sounds/swoosh.mp3
      # - assets/sounds/crystal.mp3
      - assets/sounds/bFrog.mp3
      # - assets/sounds/digital.mp3